name: Run MATLAB Tests on self-hosted runner
on: [push]
jobs:
  my-job:
    name: Run MATLAB Tests
    runs-on: self-hosted
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Checkout LFS objects
        run: "C:\Program Files\Git\cmd\git.exe" lfs checkout
      - name: Run tests
        uses: matlab-actions/run-tests@v2
        with: 
          test-results-junit: test-results/results.xml
          logging-level: detailed